# Generated by Django 4.1.3 on 2022-11-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(choices=[(1, '*'), (2, '**')], null=True),
        ),
    ]
